# Generated by Django 3.1.3 on 2021-03-25 10:41

import course.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='video',
            field=models.FileField(storage=course.storage.OverwriteStorage(), upload_to='media'),
        ),
    ]
